############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Research"
url = "/research"
weight = 3

[[main]]
name = "Teaching"
url = "/teaching"
weight = 4

[[main]]
name = "DH Projects"
url = "/dh"
weight = 5

[[main]]
parent = "DH Projects"
name = "Canadian Modernist Magazines Project"
url = "/dh/canadian-modernist-magazines-project"

[[main]]
parent = "DH Projects"
name = "Mary Butts Letters Project"
url = "/dh/mary-butts-letters-project"

[[main]]
parent = "DH Projects"
name = "Canadian HSS Commons"
url = "/dh/hss-commons"

[[main]]
parent = "DH Projects"
name = "May Day Digital Critical Edition"
url = "/dh/may-day"

[[main]]
parent = "DH Projects"
name = "Media Manifesto"
url = "/dh/media-manifesto"

[[main]]
parent = "DH Projects"
name = "MySQL database and OpenRefine workflow"
url = "/dh/mysql-openrefine-workflow"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Research"
url = "/research"
weight = 2

[[footer]]
name = "Teaching"
url = "/teaching"
weight = 3

[[footer]]
name = "DH Projects"
url = "/dh"
weight = 4
